### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by Petalses** [univeous/koishi-plugin-emojimix#1]
![AC414FA0-4DF0-4129-9C23-25F320CF57B9](https://user-images.githubusercontent.com/104431661/170545217-25d6b50a-c582-44fc-8be7-470451b1b6c2.png)
![503140D3-58C9-4DEB-A67B-CAE10F174D0A](https://user-images.githubusercontent.com/104431661/170545248-c2b687f2-ead3-41b9-abbf-2c88a5262bf0.png)

**Comment by univeous** [comment]
两个emoji之间加一个空格就好了，不过这里确实可以优化一下

**Comment by Petalses** [comment]
群里跟私聊指令不一样捏
![83251BFE-4EFA-43F1-9283-809FC4C0DC21](https://user-images.githubusercontent.com/104431661/170626409-bb562913-c6fd-434d-a5cc-4dc6baa87129.png)
![34BBCF4D-8EED-4F2F-AFC8-90F73670734B](https://user-images.githubusercontent.com/104431661/170626433-16a7c46c-4a5b-4b95-afd5-972bf76aa735.png)

**Comment by univeous** [comment]
1.2.0已经支持两个emoji之间不打空格了。


> 群里跟私聊指令不一样捏

群里发不出来多半是风控问题，建议看一下gocq的日志

**Comment by Petalses** [comment]
确实是风控，不过更新完无法解析包
![968C213D-A664-4F24-B311-0423E40106EE](https://user-images.githubusercontent.com/104431661/170632232-8dd3412b-fa8a-4ece-80ca-742f1c6d7d56.jpeg)

**Comment by univeous** [comment]
我的😥
已经修了
