### ISSUE TITLE
整理了一份emojikitchen的数据 啥时候更新一哈？

### ISSUE THREAD

**Issue by Fuduji95** [univeous/koishi-plugin-emojimix#2]
[data.json](https://github.com/univeous/koishi-plugin-emojimix/files/14954617/data.json)

**Comment by univeous** [comment]
请问一下数据源？我看看能不能做个自动更新的

**Comment by Fuduji95** [comment]
> 请问一下数据源？我看看能不能做个自动更新的

额  手动爬的https://emojikitchen.dev/的js文件里面的数据

**Comment by univeous** [comment]
新版本更新了相关的配置
