### ISSUE TITLE
bug: npm 上的 1.4.0 版本是空包

### ISSUE THREAD

**Issue by H4M5TER** [univeous/koishi-plugin-emojimix#3]
没有 README.md 和 package.json 以外的文件

**Comment by univeous** [comment]
非常抱歉，在1.4.1中修复
![5b3d0d3fe54fd86f9480165a7bd83d5b](https://github.com/univeous/koishi-plugin-emojimix/assets/40604180/02df127e-7d45-4d2c-9137-1267521149f8)
